github: [Hawkynt]
tidelift: [nuget/FrameworkExtensions.Backports, nuget/FrameworkExtensions.Corlib, nuget/FrameworkExtensions.DirectoryServices, nuget/FrameworkExtensions.System.Drawing, nuget/FrameworkExtensions.System.Windows.Forms, nuget/FrameworkExtensions.PresentationCore]
custom: ["https://www.paypal.me/hawkynt"]